### PR TITLE
ember-cli 0.2.3

### PR DESCRIPTION
**Pull request by dustinfarris**
This bumps our internal ember-cli to v0.2.3.

The PR is big as a lot needed updating.  In summary:

* All dependencies are updated to the new addon blueprint
* Sinon received a minor upgrade
* Use the new assert arg now required in ember-qunit tests
* Use node 0.12 on circleci tests
* Updated acceptance tests to return promises, avoiding the need to explicitly stop/start qunit (see: https://github.com/rwjblue/ember-qunit#async-example)

### CODE REVIEW

**Comment by stefanpenner** [comment]
```js
not ok 3 PhantomJS 1.9 - Acceptance: CRUD Failure: Permission denied error
    ---
        actual: >
            null
        message: >
            beforeEach failed on Permission denied error: 'undefined' is not a function (evaluating 'this.Router.reopen({
                      location: 'none'
                    })')
        Log: >

```

**Comment by stefanpenner** [comment]
i submitted a PR quick fixes the issue https://github.com/dustinfarris/ember-django-adapter/pull/82

**Comment by dustinfarris** [comment]
@benkonrath this should be good to merge

File: .gitignore [hunk 1]
```diff
@@ -9,7 +9,6 @@
 /bower_components
 
 # misc
-/.idea
```
Comment (benkonrath) [inline .gitignore]: I use PyCharm so this ignore is useful for me.

File: .travis.yml [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+  - "npm config set spin false"
+  - "npm install -g npm@^2"
+
+install:
+  - npm install -g bower
+  - npm install
+  - bower install
+
+script:
+  - npm test
```
Comment (benkonrath) [inline .travis.yml]: Do you also want to run the tests on travis or did this just come in through the ember cli update?

**Comment by benkonrath** [comment]
Looks good. Thanks for the doing the work on this - there are some nice improvements of the tests and it's nice to see that things are still working with the new versions of ember and ember-data.

I noticed you renamed the `integration` directory to `acceptance`. Is this required by ember-cli or is this just a better name? It's fine by me, I'm just curious.

The README should also be updated to indicate that this adapter works with ember-cli 0.2.3, ember 1.11.1 and ember-data 1.0.0-beta.16.1.

So it just the .gitignore and the question about the travis and then I'll merge it.

File: .travis.yml (hunk 2 above)
Comment (dustinfarris) [inline .travis.yml]: That came with `ember init`.  I didn't bother deleting it since it would just have to be deleted every time.  I suppose we could add it to .gitignore.  It's also good inspiration for our own circleci config.

**Comment by dustinfarris** [comment]
"acceptance" tests seems to be the _de facto_ terminology in Ember world.  I'm indifferent in general, but would like to stay consistent with the ecosystem.

File: .gitignore (hunk 1 above)
Comment (dustinfarris) [inline .gitignore]: Will fix.  I'll also add `.travis.yml` while I'm at it.

Comment (benkonrath) [inline .gitignore]: Ok, I'll merge this PR once you update this. Thanks.

**Comment by dustinfarris** [comment]
I think we're good here.
